import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/my_pic.png";
import AnimatedText from "@/components/AnimatedText";
import SKills from "@/components/SKills";
import Link from "next/link";
import { LinkArrow } from "@/components/svgs";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="-mt-10">
        <div className="flex items-start text-dark w-full min-h-screen dark:text-light">
          <Layout>
            <div className="flex items-center sm:-mt-16 justify-between w-full sm:flex-col">
              <div className="flex items-center self-center flex-col w-full sm:order-2">
                <SKills />
                <AnimatedText
                  text="Turning Vision Into Reality With Code And Design."
                  className="text-3xl my-4 sm:text-xl sm:my-6"
                />
                <p className="text-2xl sm:text-lg sm:mb-10 sm:w-[80vw]">
                  As a skilled FrontEnd developer, I am dedicated to turning
                  ideas into innovative web applications which showcases my
                  expertise in React.js and Web Development.
                </p>
              </div>
              {/* show in large hide in small */}
              <div className="mr-20 sm:mr-0 sm:my-10 sm:w-[75vw] w-[50vw]">
                <Image
                  src={profilePic}
                  alt="profile"
                  width={400}
                  height={400}
                  className=" rounded-full"
                  priority
                />
              </div>
            </div>
            <div className="flex items-center self-start mt-10 sm:mt-0 ml-10 sm:ml-0 sm:flex-col sm:gap-5">
              <Link
                href={"/resume.pdf"}
                target="_blank"
                className="flex items-center bg-dark text-light p-2.5 px-6 sm:px-3 sm:p-3 rounded-lg text-lg sm:text-sm font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:border-light"
                download={true}
              >
                Resume <LinkArrow className={"w-6 ml-1"} />
              </Link>
              <Link
                href="mailto:salmanlaw890@gmail.com"
                target={"_blank"}
                className="ml-4 text-2xl sm:xl font-medium capitalize text-dark underline dark:text-light"
              >
                Contact Me
              </Link>
            </div>
          </Layout>
          <HireMe />
          
        </div>
        <div className="absolute left-8 sm:left-4 top-[35rem] inline-block w-24 sm:w-16">
            <Image src={lightBulb} alt="light" className="w-full h-[80%]" />
          </div>
      </main>
    </>
  );
}
